dist: trusty

language: node_js
node_js: "stable"

install:
    - yarn install

env:
  # add env variables here

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: ./public
  on:
    branch: master  
script:
    - yarn run test
